pre-ommit hook for black and flake8
facebookresearch/labgraph pull request #76
Opened 2022-04-18 20:40 UTC by dtemir

## Description

I think it would be a good idea to standardize the code contributed to LabGraph by having contributors use `pre-commit` hook that will automatically run [`black`](https://github.com/psf/black) and [`flake8`](https://github.com/PyCQA/flake8) when the user makes a commit.

That way as users keep committing changes, the new code will automatically follow good standards.

Fixes #74 

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Checklist:

- [X] New and existing unit tests pass locally with these changes?
- [X] Has code been commented, particularly in hard-to-understand areas?
- [X] Have you made corresponding changes to the documentation?

2022-04-18 20:43 UTC, dtemir commented
@jfResearchEng please let me know if that'd be a useful change, but feel free to close the PR if you think it's unnecessary.

2022-04-18 21:04 UTC, dtemir commented
One more idea:
If this would be useful, I think it would be a good idea to run this

**Install pre-commit**:

```bash
pip install pre-commit
```

**Install the git hooks script**:

```bash
pre-commit install
```

It uses a file called `.pre-commit-config.yaml` to create a Git hook `.git/hooks/pre-commit`

**Apply the hook to all files**:
https://pre-commit.com/#4-optional-run-against-all-the-files

```bash
pre-commit run --all-files
```

To level everything up first

2022-04-19 23:45 UTC, jfResearchEng commented on docs/tools/codetools/README.md
> +pre-commit install
When testing with mac, the following error appears: "pre-commit not found"
The error can be fixed using: https://github.com/pre-commit/pre-commit/issues/1537

2022-04-19 23:46 UTC, jfResearchEng requested changes
Shall a common error session be added for an improvement for mac users.

2024-07-07 14:46 UTC, closed without merging